name: flutter_genui_kit_example
publish_to: none

environment:
  sdk: ">=3.3.0 <4.0.0"
  flutter: ">=3.24.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_genui_kit:
    path: ../

flutter:
  uses-material-design: true
